CREATE TABLE IF NOT EXISTS informes (
  id SERIAL PRIMARY KEY,
  postulante_id INTEGER NULL REFERENCES postulantes(id) ON UPDATE CASCADE ON DELETE SET NULL,
  vacancy_id INTEGER NULL REFERENCES vacancies(id) ON UPDATE CASCADE ON DELETE SET NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'borrador',
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS informes_generales (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  nombre_completo TEXT NULL,
  direccion TEXT NULL,
  sexo TEXT NULL,
  edad TEXT NULL,
  fecha_nacimiento TEXT NULL,
  lugar_nacimiento TEXT NULL,
  cui TEXT NULL,
  extendida TEXT NULL,
  estado_civil TEXT NULL,
  licencia_conducir TEXT NULL,
  licencia_tipo TEXT NULL,
  licencia_numero TEXT NULL,
  licencia_vigencia TEXT NULL,
  numero_documento TEXT NULL,
  nit TEXT NULL,
  igss TEXT NULL,
  irtra TEXT NULL,
  pasaporte TEXT NULL,
  visa_americana TEXT NULL,
  tel_casa TEXT NULL,
  tel_celular TEXT NULL,
  tel_emergencia TEXT NULL,
  contacto_emergencia TEXT NULL,
  parentesco TEXT NULL,
  email TEXT NULL,
  trabaja_actualmente TEXT NULL,
  empresa TEXT NULL,
  empresa_solicitante TEXT NULL,
  labora_para_la_empresa TEXT NULL,
  puesto_aplica TEXT NULL,
  medio_transporte TEXT NULL,
  religion TEXT NULL,
  tipo_sangre TEXT NULL,
  estatura TEXT NULL,
  peso TEXT NULL,
  cicatrices TEXT NULL,
  cabello TEXT NULL,
  tipo_cabello TEXT NULL,
  apodo TEXT NULL,
  profesion TEXT NULL,
  pretension TEXT NULL,
  comentarios TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_familiares (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  nombre_padre TEXT NULL,
  edad_padre TEXT NULL,
  fecha_nacimiento_padre TEXT NULL,
  originario_padre TEXT NULL,
  vive_padre TEXT NULL,
  vive_con_padre TEXT NULL,
  escolaridad_padre TEXT NULL,
  profesion_padre TEXT NULL,
  residencia_padre TEXT NULL,
  nombre_madre TEXT NULL,
  edad_madre TEXT NULL,
  fecha_nacimiento_madre TEXT NULL,
  originario_madre TEXT NULL,
  vive_madre TEXT NULL,
  vive_con_madre TEXT NULL,
  escolaridad_madre TEXT NULL,
  profesion_madre TEXT NULL,
  residencia_madre TEXT NULL,
  reside_en_pareja TEXT NULL,
  nombre_pareja TEXT NULL,
  edad_pareja TEXT NULL,
  fecha_nacimiento_pareja TEXT NULL,
  originario_pareja TEXT NULL,
  viven_juntos TEXT NULL,
  tiempo_relacion TEXT NULL,
  escolaridad_pareja TEXT NULL,
  profesion_pareja TEXT NULL,
  residencia_pareja TEXT NULL,
  comentarios TEXT NULL,
  hermanos JSONB NULL,
  hijos JSONB NULL
);

CREATE TABLE IF NOT EXISTS informes_salud (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  servicios_medicos TEXT NULL,
  frecuencia_medico TEXT NULL,
  servicios_con_que_cuenta TEXT NULL,
  enfermedad_congenita TEXT NULL,
  deformidad_congenita TEXT NULL,
  alergias TEXT NULL,
  enf_ojos TEXT NULL,
  usa_lentes TEXT NULL,
  deberia_usar_lentes TEXT NULL,
  oye_bien TEXT NULL,
  usa_aparatos_oir TEXT NULL,
  enf_oidos TEXT NULL,
  enf_dentales TEXT NULL,
  enf_tiroides TEXT NULL,
  enf_respiratorias TEXT NULL,
  enf_pulmones TEXT NULL,
  enf_corazon TEXT NULL,
  tension_arterial TEXT NULL,
  sistema_circulatorio TEXT NULL,
  enf_digestivas TEXT NULL,
  enf_higado TEXT NULL,
  niveles_azucar TEXT NULL,
  alteraciones_metabolicas TEXT NULL,
  enf_renales TEXT NULL,
  infecciones_urinarias TEXT NULL,
  enf_piel TEXT NULL,
  enf_infecciosas TEXT NULL,
  ingresos_hospitalarios TEXT NULL,
  operaciones TEXT NULL,
  accidentes TEXT NULL,
  fracturas TEXT NULL,
  secuelas TEXT NULL,
  enf_cronicas TEXT NULL,
  enf_contagiosas TEXT NULL,
  tratamientos_psicologicos TEXT NULL,
  enf_transmision_sexual TEXT NULL,
  toma_medicamentos TEXT NULL,
  medicamentos_permanentes TEXT NULL,
  enferma_frecuencia TEXT NULL,
  desmayos TEXT NULL,
  tratamiento_medico TEXT NULL,
  asistio_ultimas_semanas TEXT NULL,
  contacto_covid TEXT NULL,
  sintomas_covid TEXT NULL,
  positivo_covid TEXT NULL,
  fecha_contagio TEXT NULL,
  familiar_covid TEXT NULL,
  fecha_contagio_familiar TEXT NULL,
  vacunado_covid TEXT NULL,
  cantidad_dosis TEXT NULL,
  tipo_vacuna TEXT NULL,
  problemas_ginecologicos TEXT NULL,
  problemas_mamarios TEXT NULL,
  examen_rutina TEXT NULL,
  revisiones_ginecologicas TEXT NULL,
  embarazada TEXT NULL,
  talla_camisa TEXT NULL,
  talla_pantalon TEXT NULL,
  talla_calzado TEXT NULL,
  altura TEXT NULL,
  peso TEXT NULL,
  complexion TEXT NULL,
  usted_fuma TEXT NULL,
  fuma_actualmente TEXT NULL,
  fumaba_anteriormente TEXT NULL,
  ha_fumado TEXT NULL,
  ingiere_alcohol TEXT NULL,
  actualmente_bebe TEXT NULL,
  ha_ingerido_alcohol TEXT NULL,
  ex_alcoholico TEXT NULL,
  consume_drogas TEXT NULL,
  conoce_drogas TEXT NULL,
  ha_probado_drogas TEXT NULL,
  practica_deporte TEXT NULL,
  deporte_practica TEXT NULL,
  frecuencia_ejercicio TEXT NULL,
  club_deportivo TEXT NULL,
  horas_sueno TEXT NULL,
  padece_insomnio TEXT NULL,
  toma_somniferos TEXT NULL,
  tareas_domesticas TEXT NULL,
  actividades_tiempo_libre TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_academicos (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  universitario JSONB NULL,
  diversificado JSONB NULL,
  primaria JSONB NULL,
  tecnico JSONB NULL,
  conocimientos_generales JSONB NULL
);

CREATE TABLE IF NOT EXISTS informes_antecedentes (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  deshonestidad TEXT NULL,
  mentido_empleo TEXT NULL,
  beneficio_ilicito TEXT NULL,
  uso_indebido_info TEXT NULL,
  uso_suministros TEXT NULL,
  problemas_laborales TEXT NULL,
  discusiones_superiores TEXT NULL,
  acta_administrativa TEXT NULL,
  sobornos TEXT NULL,
  conoce_delincuentes TEXT NULL,
  miembro_sindicato TEXT NULL,
  asociado_grupos TEXT NULL,
  beneficiado_ilicito TEXT NULL,
  amistad_grupos TEXT NULL,
  amistad_antecedentes TEXT NULL,
  familia_problemas_legales TEXT NULL,
  efectivo_cargo TEXT NULL,
  sobrantes_faltantes TEXT NULL,
  auto_prestamos TEXT NULL,
  jineteo_efectivo TEXT NULL,
  familiar_detenido TEXT NULL,
  cargos_cometida TEXT NULL,
  ayudado_ilicito TEXT NULL,
  oculta_info TEXT NULL,
  actividad_ilicita TEXT NULL,
  mintio_informacion TEXT NULL,
  robo_superior100 TEXT NULL,
  tomado_productos TEXT NULL,
  regalos_valor TEXT NULL,
  despedido_robo TEXT NULL,
  conoce_droga TEXT NULL,
  consume_drogas TEXT NULL,
  vida_drogas TEXT NULL,
  trabajo_drogas TEXT NULL,
  divulga_info TEXT NULL,
  tarjeta_credito TEXT NULL,
  falsificado_documentos TEXT NULL,
  fraude_extorsion TEXT NULL,
  acto_inmoral TEXT NULL,
  relacion_laboral TEXT NULL,
  tramites_no_autorizados TEXT NULL,
  problemas_personales TEXT NULL,
  atentado_vida_propia TEXT NULL,
  atentado_vida_otros TEXT NULL,
  ebriedad_trabajo TEXT NULL,
  estupefacientes_trabajo TEXT NULL,
  deudas_economicas TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_laborales (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  se_encuentra_laborando TEXT NULL,
  sosten_economico TEXT NULL,
  ingreso_aproximado TEXT NULL,
  comentario_general TEXT NULL,
  empresas JSONB NULL
);

CREATE TABLE IF NOT EXISTS informes_economicos (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  ingresos_actuales TEXT NULL,
  salario_pareja TEXT NULL,
  recibe_remesa TEXT NULL,
  ingreso_aprox TEXT NULL,
  otros_ingresos TEXT NULL,
  origen_ingreso TEXT NULL,
  ingreso_adicional TEXT NULL,
  laborando_actualmente TEXT NULL,
  empresa TEXT NULL,
  ultimo_salario TEXT NULL,
  posee_creditos TEXT NULL,
  cuantos_creditos TEXT NULL,
  posee_tarjetas TEXT NULL,
  cuantas_tarjetas TEXT NULL,
  atraso_cuotas TEXT NULL,
  atraso_tarjetas TEXT NULL,
  demanda_financiera TEXT NULL,
  embargos_activos TEXT NULL,
  promedio_gastos TEXT NULL,
  salario_ofrecido TEXT NULL,
  ingreso_familiar TEXT NULL,
  cuentas_monetarias TEXT NULL,
  cuentas_ahorro TEXT NULL,
  labora_actualmente TEXT NULL,
  ultimo_salario_devengado TEXT NULL,
  ingreso_actual TEXT NULL,
  ingresos_adicionales TEXT NULL,
  ingreso_total_familiar TEXT NULL,
  hipoteca TEXT NULL,
  alquiler TEXT NULL,
  mantenimiento TEXT NULL,
  seguridad TEXT NULL,
  agua TEXT NULL,
  luz TEXT NULL,
  gas TEXT NULL,
  internet TEXT NULL,
  telefono_fijo TEXT NULL,
  cable TEXT NULL,
  alimentacion TEXT NULL,
  servicios_domesticos TEXT NULL,
  extraccion_desechos TEXT NULL,
  recreacion TEXT NULL,
  vestuario TEXT NULL,
  medicamentos TEXT NULL,
  estudios_propios TEXT NULL,
  estudios_terceros TEXT NULL,
  ahorro TEXT NULL,
  pago_tarjeta TEXT NULL,
  pago_prestamo TEXT NULL,
  pago_consumo TEXT NULL,
  pago_visa TEXT NULL,
  pago_extra TEXT NULL,
  adquisicion_bienes TEXT NULL,
  transporte TEXT NULL,
  combustible TEXT NULL,
  pension TEXT NULL,
  otros_gastos TEXT NULL,
  total_egresos TEXT NULL,
  aportantes JSONB NULL,
  tarjetas JSONB NULL,
  visas JSONB NULL,
  prestamos JSONB NULL,
  propiedad_nombre_propia TEXT NULL,
  propiedad_nombre_padres TEXT NULL,
  propiedad_nombre_pareja TEXT NULL,
  propiedad_nombre_ambos TEXT NULL,
  bienes_inmuebles JSONB NULL,
  vehiculos JSONB NULL,
  demanda_judicial TEXT NULL,
  antecedente_policiaco TEXT NULL,
  antecedente_penal TEXT NULL,
  ha_demandado_persona TEXT NULL,
  ha_demandado_empresa TEXT NULL,
  ha_recibido_denuncia TEXT NULL,
  posee_armas TEXT NULL,
  licencia_armas TEXT NULL,
  ha_estado_detenido TEXT NULL,
  posee_proceso_legal TEXT NULL,
  registro_buro TEXT NULL,
  registro_infornet TEXT NULL,
  posee_otra_deuda TEXT NULL,
  es_fiador TEXT NULL,
  comentarios_referencias TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_vivienda (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo_domicilio TEXT NULL,
  ubicacion TEXT NULL,
  servicios_basicos TEXT NULL,
  residencia TEXT NULL,
  propietario_nombre TEXT NULL,
  parentesco_propietario TEXT NULL,
  clasificacion_poblacion TEXT NULL,
  color_fachada TEXT NULL,
  color_puertas TEXT NULL,
  caracteristicas_domicilio TEXT NULL,
  habitaciones_dormir TEXT NULL,
  ambientes_totales TEXT NULL,
  estado_domicilio TEXT NULL,
  tipo_construccion TEXT NULL,
  material_techo TEXT NULL,
  material_piso TEXT NULL,
  niveles_domicilio TEXT NULL,
  parque_domicilio TEXT NULL,
  tamano_propiedad TEXT NULL,
  television TEXT NULL,
  cantidad_televisores TEXT NULL,
  servicio_cable TEXT NULL,
  internet TEXT NULL,
  computadora TEXT NULL,
  cantidad_computadoras TEXT NULL,
  equipo_sonido TEXT NULL,
  microondas TEXT NULL,
  refrigerador TEXT NULL,
  estufa TEXT NULL,
  tiempo_vivir TEXT NULL,
  habitantes_totales TEXT NULL,
  distancia_trabajo TEXT NULL,
  tiempo_traslado TEXT NULL,
  medio_transporte TEXT NULL,
  habitantes_vivienda JSONB NULL,
  sistema_agua_potable TEXT NULL,
  sistema_alcantarillado_aguas_servidas TEXT NULL,
  sistema_desague_pluviales_drenajes TEXT NULL,
  sistema_alumbrado_publico TEXT NULL,
  servicio_energia_electrica TEXT NULL,
  servicio_recoleccion_basura TEXT NULL,
  servicio_gas_propano TEXT NULL,
  servicio_seguridad_publica TEXT NULL,
  servicio_asistencia_medica TEXT NULL,
  establecimientos_educativos TEXT NULL,
  servicio_transporte_publico TEXT NULL,
  servicio_telecomunicaciones_telefonia_publica TEXT NULL,
  pavimentacion TEXT NULL,
  servicio_vigilancia_privada TEXT NULL,
  existe_vandalismo_zona TEXT NULL,
  hay_farmaco_dependencia TEXT NULL,
  zona_considerada_roja TEXT NULL,
  zona_alta_densidad_poblacion TEXT NULL,
  ha_sido_victima_delito_domicilio TEXT NULL,
  clase_social_zona TEXT NULL,
  nivel_peligrosidad TEXT NULL,
  referencias_vecinos TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_redes (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  usa_redes_sociales TEXT NULL,
  deja_actividades_por_redes TEXT NULL,
  hora_mas_activa TEXT NULL,
  revisa_antes_dormir TEXT NULL,
  tiempo_en_redes TEXT NULL,
  tiempo_chat_amigos TEXT NULL,
  tiempo_chat_familiares TEXT NULL,
  tiempo_platica_pareja TEXT NULL,
  ha_dejado_redes TEXT NULL,
  tipo_contenido TEXT NULL,
  captura_perfil TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_referencias (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  referencias_personales JSONB NULL,
  referencias_familiares JSONB NULL,
  referencias_vecindario JSONB NULL
);

CREATE TABLE IF NOT EXISTS informes_entrevista (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  presentacion_hora TEXT NULL,
  comentario_presentacion TEXT NULL,
  vestimenta_adecuada TEXT NULL,
  desarrollo_verbal TEXT NULL,
  objetivo_corto_personal TEXT NULL,
  objetivo_mediano_personal TEXT NULL,
  objetivo_largo_personal TEXT NULL,
  objetivo_corto_laboral TEXT NULL,
  objetivo_mediano_laboral TEXT NULL,
  objetivo_largo_laboral TEXT NULL,
  espera_empresa TEXT NULL,
  tiene_familiares TEXT NULL,
  presento_documentacion TEXT NULL,
  carece_antecedentes TEXT NULL,
  alteraciones_documentacion TEXT NULL
);

CREATE TABLE IF NOT EXISTS informes_anexos (
  informe_id INTEGER PRIMARY KEY REFERENCES informes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  vivienda JSONB NULL,
  dpi JSONB NULL,
  rtu JSONB NULL,
  cgc JSONB NULL,
  mspas JSONB NULL,
  recede JSONB NULL,
  migracion JSONB NULL,
  renas JSONB NULL,
  antecedentes JSONB NULL
);
