import { DataTypes, Model } from 'sequelize';

export class InformeSalud extends Model {}

export const initInformeSalud = (sequelize) => {
  InformeSalud.init(
    {
      informeId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        field: 'informe_id',
        references: { model: 'informes', key: 'id' },
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE'
      },
      serviciosMedicos: { type: DataTypes.TEXT, allowNull: true, field: 'servicios_medicos' },
      frecuenciaMedico: { type: DataTypes.TEXT, allowNull: true, field: 'frecuencia_medico' },
      serviciosConQueCuenta: { type: DataTypes.TEXT, allowNull: true, field: 'servicios_con_que_cuenta' },
      enfermedadCongenita: { type: DataTypes.TEXT, allowNull: true, field: 'enfermedad_congenita' },
      deformidadCongenita: { type: DataTypes.TEXT, allowNull: true, field: 'deformidad_congenita' },
      alergias: { type: DataTypes.TEXT, allowNull: true },
      enfOjos: { type: DataTypes.TEXT, allowNull: true, field: 'enf_ojos' },
      usaLentes: { type: DataTypes.TEXT, allowNull: true, field: 'usa_lentes' },
      deberiaUsarLentes: { type: DataTypes.TEXT, allowNull: true, field: 'deberia_usar_lentes' },
      oyeBien: { type: DataTypes.TEXT, allowNull: true, field: 'oye_bien' },
      usaAparatosOir: { type: DataTypes.TEXT, allowNull: true, field: 'usa_aparatos_oir' },
      enfOidos: { type: DataTypes.TEXT, allowNull: true, field: 'enf_oidos' },
      enfDentales: { type: DataTypes.TEXT, allowNull: true, field: 'enf_dentales' },
      enfTiroides: { type: DataTypes.TEXT, allowNull: true, field: 'enf_tiroides' },
      enfRespiratorias: { type: DataTypes.TEXT, allowNull: true, field: 'enf_respiratorias' },
      enfPulmones: { type: DataTypes.TEXT, allowNull: true, field: 'enf_pulmones' },
      enfCorazon: { type: DataTypes.TEXT, allowNull: true, field: 'enf_corazon' },
      tensionArterial: { type: DataTypes.TEXT, allowNull: true, field: 'tension_arterial' },
      sistemaCirculatorio: { type: DataTypes.TEXT, allowNull: true, field: 'sistema_circulatorio' },
      enfDigestivas: { type: DataTypes.TEXT, allowNull: true, field: 'enf_digestivas' },
      enfHigado: { type: DataTypes.TEXT, allowNull: true, field: 'enf_higado' },
      nivelesAzucar: { type: DataTypes.TEXT, allowNull: true, field: 'niveles_azucar' },
      alteracionesMetabolicas: { type: DataTypes.TEXT, allowNull: true, field: 'alteraciones_metabolicas' },
      enfRenales: { type: DataTypes.TEXT, allowNull: true, field: 'enf_renales' },
      infeccionesUrinarias: { type: DataTypes.TEXT, allowNull: true, field: 'infecciones_urinarias' },
      enfPiel: { type: DataTypes.TEXT, allowNull: true, field: 'enf_piel' },
      enfInfecciosas: { type: DataTypes.TEXT, allowNull: true, field: 'enf_infecciosas' },
      ingresosHospitalarios: { type: DataTypes.TEXT, allowNull: true, field: 'ingresos_hospitalarios' },
      operaciones: { type: DataTypes.TEXT, allowNull: true },
      accidentes: { type: DataTypes.TEXT, allowNull: true },
      fracturas: { type: DataTypes.TEXT, allowNull: true },
      secuelas: { type: DataTypes.TEXT, allowNull: true },
      enfCronicas: { type: DataTypes.TEXT, allowNull: true, field: 'enf_cronicas' },
      enfContagiosas: { type: DataTypes.TEXT, allowNull: true, field: 'enf_contagiosas' },
      tratamientosPsicologicos: { type: DataTypes.TEXT, allowNull: true, field: 'tratamientos_psicologicos' },
      enfTransmisionSexual: { type: DataTypes.TEXT, allowNull: true, field: 'enf_transmision_sexual' },
      tomaMedicamentos: { type: DataTypes.TEXT, allowNull: true, field: 'toma_medicamentos' },
      medicamentosPermanentes: { type: DataTypes.TEXT, allowNull: true, field: 'medicamentos_permanentes' },
      enfermaFrecuencia: { type: DataTypes.TEXT, allowNull: true, field: 'enferma_frecuencia' },
      desmayos: { type: DataTypes.TEXT, allowNull: true },
      tratamientoMedico: { type: DataTypes.TEXT, allowNull: true, field: 'tratamiento_medico' },
      asistioUltimasSemanas: { type: DataTypes.TEXT, allowNull: true, field: 'asistio_ultimas_semanas' },
      contactoCovid: { type: DataTypes.TEXT, allowNull: true, field: 'contacto_covid' },
      sintomasCovid: { type: DataTypes.TEXT, allowNull: true, field: 'sintomas_covid' },
      positivoCovid: { type: DataTypes.TEXT, allowNull: true, field: 'positivo_covid' },
      fechaContagio: { type: DataTypes.TEXT, allowNull: true, field: 'fecha_contagio' },
      familiarCovid: { type: DataTypes.TEXT, allowNull: true, field: 'familiar_covid' },
      fechaContagioFamiliar: { type: DataTypes.TEXT, allowNull: true, field: 'fecha_contagio_familiar' },
      vacunadoCovid: { type: DataTypes.TEXT, allowNull: true, field: 'vacunado_covid' },
      cantidadDosis: { type: DataTypes.TEXT, allowNull: true, field: 'cantidad_dosis' },
      tipoVacuna: { type: DataTypes.TEXT, allowNull: true, field: 'tipo_vacuna' },
      problemasGinecologicos: { type: DataTypes.TEXT, allowNull: true, field: 'problemas_ginecologicos' },
      problemasMamarios: { type: DataTypes.TEXT, allowNull: true, field: 'problemas_mamarios' },
      examenRutina: { type: DataTypes.TEXT, allowNull: true, field: 'examen_rutina' },
      revisionesGinecologicas: { type: DataTypes.TEXT, allowNull: true, field: 'revisiones_ginecologicas' },
      embarazada: { type: DataTypes.TEXT, allowNull: true },
      tallaCamisa: { type: DataTypes.TEXT, allowNull: true, field: 'talla_camisa' },
      tallaPantalon: { type: DataTypes.TEXT, allowNull: true, field: 'talla_pantalon' },
      tallaCalzado: { type: DataTypes.TEXT, allowNull: true, field: 'talla_calzado' },
      altura: { type: DataTypes.TEXT, allowNull: true },
      peso: { type: DataTypes.TEXT, allowNull: true },
      complexion: { type: DataTypes.TEXT, allowNull: true },
      ustedFuma: { type: DataTypes.TEXT, allowNull: true, field: 'usted_fuma' },
      fumaActualmente: { type: DataTypes.TEXT, allowNull: true, field: 'fuma_actualmente' },
      fumabaAnteriormente: { type: DataTypes.TEXT, allowNull: true, field: 'fumaba_anteriormente' },
      haFumado: { type: DataTypes.TEXT, allowNull: true, field: 'ha_fumado' },
      ingiereAlcohol: { type: DataTypes.TEXT, allowNull: true, field: 'ingiere_alcohol' },
      actualmenteBebe: { type: DataTypes.TEXT, allowNull: true, field: 'actualmente_bebe' },
      haIngeridoAlcohol: { type: DataTypes.TEXT, allowNull: true, field: 'ha_ingerido_alcohol' },
      exAlcoholico: { type: DataTypes.TEXT, allowNull: true, field: 'ex_alcoholico' },
      consumeDrogas: { type: DataTypes.TEXT, allowNull: true, field: 'consume_drogas' },
      conoceDrogas: { type: DataTypes.TEXT, allowNull: true, field: 'conoce_drogas' },
      haProbadoDrogas: { type: DataTypes.TEXT, allowNull: true, field: 'ha_probado_drogas' },
      practicaDeporte: { type: DataTypes.TEXT, allowNull: true, field: 'practica_deporte' },
      deportePractica: { type: DataTypes.TEXT, allowNull: true, field: 'deporte_practica' },
      frecuenciaEjercicio: { type: DataTypes.TEXT, allowNull: true, field: 'frecuencia_ejercicio' },
      clubDeportivo: { type: DataTypes.TEXT, allowNull: true, field: 'club_deportivo' },
      horasSueno: { type: DataTypes.TEXT, allowNull: true, field: 'horas_sueno' },
      padeceInsomnio: { type: DataTypes.TEXT, allowNull: true, field: 'padece_insomnio' },
      tomaSomniferos: { type: DataTypes.TEXT, allowNull: true, field: 'toma_somniferos' },
      tareasDomesticas: { type: DataTypes.TEXT, allowNull: true, field: 'tareas_domesticas' },
      actividadesTiempoLibre: { type: DataTypes.TEXT, allowNull: true, field: 'actividades_tiempo_libre' }
    },
    {
      sequelize,
      tableName: 'informes_salud',
      modelName: 'InformeSalud',
      underscored: true,
      timestamps: false
    }
  );
  return InformeSalud;
};
