import { DataTypes, Model } from 'sequelize';

export class InformeEconomicos extends Model {}

export const initInformeEconomicos = (sequelize) => {
  InformeEconomicos.init(
    {
      informeId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        field: 'informe_id',
        references: { model: 'informes', key: 'id' },
        onUpdate: 'CASCADE',
        onDelete: 'CASCADE'
      },
      ingresosActuales: { type: DataTypes.TEXT, allowNull: true, field: 'ingresos_actuales' },
      salarioPareja: { type: DataTypes.TEXT, allowNull: true, field: 'salario_pareja' },
      recibeRemesa: { type: DataTypes.TEXT, allowNull: true, field: 'recibe_remesa' },
      ingresoAprox: { type: DataTypes.TEXT, allowNull: true, field: 'ingreso_aprox' },
      otrosIngresos: { type: DataTypes.TEXT, allowNull: true, field: 'otros_ingresos' },
      origenIngreso: { type: DataTypes.TEXT, allowNull: true, field: 'origen_ingreso' },
      ingresoAdicional: { type: DataTypes.TEXT, allowNull: true, field: 'ingreso_adicional' },
      laborandoActualmente: { type: DataTypes.TEXT, allowNull: true, field: 'laborando_actualmente' },
      empresa: { type: DataTypes.TEXT, allowNull: true },
      ultimoSalario: { type: DataTypes.TEXT, allowNull: true, field: 'ultimo_salario' },
      poseeCreditos: { type: DataTypes.TEXT, allowNull: true, field: 'posee_creditos' },
      cuantosCreditos: { type: DataTypes.TEXT, allowNull: true, field: 'cuantos_creditos' },
      poseeTarjetas: { type: DataTypes.TEXT, allowNull: true, field: 'posee_tarjetas' },
      cuantasTarjetas: { type: DataTypes.TEXT, allowNull: true, field: 'cuantas_tarjetas' },
      atrasoCuotas: { type: DataTypes.TEXT, allowNull: true, field: 'atraso_cuotas' },
      atrasoTarjetas: { type: DataTypes.TEXT, allowNull: true, field: 'atraso_tarjetas' },
      demandaFinanciera: { type: DataTypes.TEXT, allowNull: true, field: 'demanda_financiera' },
      embargosActivos: { type: DataTypes.TEXT, allowNull: true, field: 'embargos_activos' },
      promedioGastos: { type: DataTypes.TEXT, allowNull: true, field: 'promedio_gastos' },
      salarioOfrecido: { type: DataTypes.TEXT, allowNull: true, field: 'salario_ofrecido' },
      ingresoFamiliar: { type: DataTypes.TEXT, allowNull: true, field: 'ingreso_familiar' },
      cuentasMonetarias: { type: DataTypes.TEXT, allowNull: true, field: 'cuentas_monetarias' },
      cuentasAhorro: { type: DataTypes.TEXT, allowNull: true, field: 'cuentas_ahorro' },
      laboraActualmente: { type: DataTypes.TEXT, allowNull: true, field: 'labora_actualmente' },
      ultimoSalarioDevengado: { type: DataTypes.TEXT, allowNull: true, field: 'ultimo_salario_devengado' },
      ingresoActual: { type: DataTypes.TEXT, allowNull: true, field: 'ingreso_actual' },
      ingresosAdicionales: { type: DataTypes.TEXT, allowNull: true, field: 'ingresos_adicionales' },
      ingresoTotalFamiliar: { type: DataTypes.TEXT, allowNull: true, field: 'ingreso_total_familiar' },
      hipoteca: { type: DataTypes.TEXT, allowNull: true },
      alquiler: { type: DataTypes.TEXT, allowNull: true },
      mantenimiento: { type: DataTypes.TEXT, allowNull: true },
      seguridad: { type: DataTypes.TEXT, allowNull: true },
      agua: { type: DataTypes.TEXT, allowNull: true },
      luz: { type: DataTypes.TEXT, allowNull: true },
      gas: { type: DataTypes.TEXT, allowNull: true },
      internet: { type: DataTypes.TEXT, allowNull: true },
      telefonoFijo: { type: DataTypes.TEXT, allowNull: true, field: 'telefono_fijo' },
      cable: { type: DataTypes.TEXT, allowNull: true },
      alimentacion: { type: DataTypes.TEXT, allowNull: true },
      serviciosDomesticos: { type: DataTypes.TEXT, allowNull: true, field: 'servicios_domesticos' },
      extraccionDesechos: { type: DataTypes.TEXT, allowNull: true, field: 'extraccion_desechos' },
      recreacion: { type: DataTypes.TEXT, allowNull: true },
      vestuario: { type: DataTypes.TEXT, allowNull: true },
      medicamentos: { type: DataTypes.TEXT, allowNull: true },
      estudiosPropios: { type: DataTypes.TEXT, allowNull: true, field: 'estudios_propios' },
      estudiosTerceros: { type: DataTypes.TEXT, allowNull: true, field: 'estudios_terceros' },
      ahorro: { type: DataTypes.TEXT, allowNull: true },
      pagoTarjeta: { type: DataTypes.TEXT, allowNull: true, field: 'pago_tarjeta' },
      pagoPrestamo: { type: DataTypes.TEXT, allowNull: true, field: 'pago_prestamo' },
      pagoConsumo: { type: DataTypes.TEXT, allowNull: true, field: 'pago_consumo' },
      pagoVisa: { type: DataTypes.TEXT, allowNull: true, field: 'pago_visa' },
      pagoExtra: { type: DataTypes.TEXT, allowNull: true, field: 'pago_extra' },
      adquisicionBienes: { type: DataTypes.TEXT, allowNull: true, field: 'adquisicion_bienes' },
      transporte: { type: DataTypes.TEXT, allowNull: true },
      combustible: { type: DataTypes.TEXT, allowNull: true },
      pension: { type: DataTypes.TEXT, allowNull: true },
      otrosGastos: { type: DataTypes.TEXT, allowNull: true, field: 'otros_gastos' },
      totalEgresos: { type: DataTypes.TEXT, allowNull: true, field: 'total_egresos' },
      aportantes: { type: DataTypes.JSONB, allowNull: true },
      tarjetas: { type: DataTypes.JSONB, allowNull: true },
      visas: { type: DataTypes.JSONB, allowNull: true },
      prestamos: { type: DataTypes.JSONB, allowNull: true },
      propiedadNombrePropia: { type: DataTypes.TEXT, allowNull: true, field: 'propiedad_nombre_propia' },
      propiedadNombrePadres: { type: DataTypes.TEXT, allowNull: true, field: 'propiedad_nombre_padres' },
      propiedadNombrePareja: { type: DataTypes.TEXT, allowNull: true, field: 'propiedad_nombre_pareja' },
      propiedadNombreAmbos: { type: DataTypes.TEXT, allowNull: true, field: 'propiedad_nombre_ambos' },
      bienesInmuebles: { type: DataTypes.JSONB, allowNull: true, field: 'bienes_inmuebles' },
      vehiculos: { type: DataTypes.JSONB, allowNull: true },
      demandaJudicial: { type: DataTypes.TEXT, allowNull: true, field: 'demanda_judicial' },
      antecedentePoliciaco: { type: DataTypes.TEXT, allowNull: true, field: 'antecedente_policiaco' },
      antecedentePenal: { type: DataTypes.TEXT, allowNull: true, field: 'antecedente_penal' },
      haDemandadoPersona: { type: DataTypes.TEXT, allowNull: true, field: 'ha_demandado_persona' },
      haDemandadoEmpresa: { type: DataTypes.TEXT, allowNull: true, field: 'ha_demandado_empresa' },
      haRecibidoDenuncia: { type: DataTypes.TEXT, allowNull: true, field: 'ha_recibido_denuncia' },
      poseeArmas: { type: DataTypes.TEXT, allowNull: true, field: 'posee_armas' },
      licenciaArmas: { type: DataTypes.TEXT, allowNull: true, field: 'licencia_armas' },
      haEstadoDetenido: { type: DataTypes.TEXT, allowNull: true, field: 'ha_estado_detenido' },
      poseeProcesoLegal: { type: DataTypes.TEXT, allowNull: true, field: 'posee_proceso_legal' },
      registroBuro: { type: DataTypes.TEXT, allowNull: true, field: 'registro_buro' },
      registroInfornet: { type: DataTypes.TEXT, allowNull: true, field: 'registro_infornet' },
      poseeOtraDeuda: { type: DataTypes.TEXT, allowNull: true, field: 'posee_otra_deuda' },
      esFiador: { type: DataTypes.TEXT, allowNull: true, field: 'es_fiador' },
      comentariosReferencias: { type: DataTypes.TEXT, allowNull: true, field: 'comentarios_referencias' }
    },
    {
      sequelize,
      tableName: 'informes_economicos',
      modelName: 'InformeEconomicos',
      underscored: true,
      timestamps: false
    }
  );
  return InformeEconomicos;
};
